### ISSUE TITLE
generate_bamfile.sh fails with absolute pathnames

### ISSUE THREAD

**Issue by cschu** [pierrj/ecc_caller#1]
When an absolute pathname (e.g. /path/to/file) is given for the input files, the tmpfile name in the cutadapt call

`cutadapt -j ${THREADS} -a AGATCGGAAGAGCACACGTCTGAACTCCAGTCA -A AGATCGGAAGAGCGTCGTGTAGGGAAAGAGTGT --nextseq-trim=20 -o tmp.trimmed.seqprep.${SAMPLE}_R1.fastq -p tmp.trimmed.seqprep.${SAMPLE}_R2.fastq ${READONE} ${READTWO}` 

will be `tmp.trimmed.seqprep./path/to/file_R[12].fastq`, which obviously doesn't exist and so the execution will fail.

**Comment by pierrj** [comment]
Yes, that makes sense. I added a note to the README, "output_name" should be a string, not a path. Thank you for point that out.

**Comment by cschu** [comment]
No worries. Would it maybe make sense to add the capability to use full paths?

**Comment by pierrj** [comment]
Yes definitely! It is on my to-do list but not sure exactly when I will get around to working on it.
